export const ACTION_GET_ORDERS = 'ACTION_GET_ORDERS';
export const ACTION_GET_MORE_ORDERS = 'ACTION_GET_MORE_ORDERS';
export const ACTION_PAY_ORDER = 'ACTION_PAY_ORDER';
export const ACTION_CREATE_ORDER = 'ACTION_CREATE_ORDER';
export const ACTION_CANCEL_ORDER = 'ACTION_CANCEL_ORDER';
export const ACTION_FINISH_ORDER = 'ACTION_FINISH_ORDER';
