export const ACTION_GET_RECIPES = 'ACTION_GET_RECIPES';

export const ACTION_CLEAR_RECIPESINCART = 'ACTION_CLEAR_RECIPESINCART';
export const ACTION_PLUS_RECIPE = 'ACTION_ADD_RECIPE';
export const ACTION_MINUS_RECIPE = 'ACTION_MINUS_RECIPE';
