export const ACTION_GET_RECIPES = 'ACTION_GET_RECIPES';

export const ACTION_CLEAR_RECIPESINCART = 'ACTION_CLEAR_RECIPESINCART';
export const ACTION_PLUS_RECIPE = 'ACTION_ADD_RECIPE';
export const ACTION_MINUS_RECIPE = 'ACTION_MINUS_RECIPE';

export const ACTION_VIEW_RECIPE = 'ACTION_VIEW_RECIPE';
export const ACTION_SET_ADDRESS = 'ACTION_SET_ADDRESS';
