export const ACTION_SEARCH_BUSINESS = 'ACTION_SEARCH_BUSINESS';

export const ACTION_LOGIN = 'ACTION_LOGIN';
export const ACTION_REGISTER = 'ACTION_REGISTER';
export const ACTION_CHECK = 'ACTION_CHECK';
export const ACTION_MODIFYPWD = 'ACTION_MODIFYPWD';
